name:                Naproche-SAD
version:             0.1.0.0
github:              "Naproche/Naproche-SAD"
license:             GPL-3

extra-source-files:
- README.md

description:         <https://github.com/Naproche/Naproche-SAD>

flags:
  debug:
    description: "Enable special debugging support"
    manual: true
    default: false
  

when:
  condition: flag(debug)
  dependencies:
  - haskell-stack-trace-plugin
  ghc-options:
  - -fplugin=StackTrace.Plugin
  - -Weverything
  - -Wno-unsafe
  - -Wno-implicit-prelude

dependencies:
- base >= 4.7 && < 5
- containers
- unordered-containers
- deepseq
- filepath
- directory
- binary
- ghc-prim
- hashable
- time
- mtl
- bytestring
- text
- split
- aeson

default-extensions:
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - LambdaCase
  - PartialTypeSignatures
  - ScopedTypeVariables

ghc-options:
  - -O2
  - -Wall
  - -fno-warn-unused-do-bind
  - -fno-warn-unused-matches
  - -fno-warn-name-shadowing

library:
  source-dirs:
    - src
    - Isabelle/src
  exposed-modules:
    - SAD.Core.Pretty
    - SAD.Core.Logging
    - SAD.Core.Message
    - SAD.Core.Provers
    - SAD.Core.Prove
    - SAD.Core.Reader
    - SAD.Core.SourcePos
    - SAD.Core.Transform
    - SAD.Core.Typed
    - SAD.Core.Cache
    - SAD.Core.Task
    - SAD.Data.Text.Block
    - SAD.Data.Instr
    - SAD.Parser.Error
    - SAD.Main
  other-modules:
    - Isabelle.Markup
    - Isabelle.Value
    - Isabelle.Naproche
    - Isabelle.Library
    - Isabelle.Properties
    - Isabelle.Symbol
    - SAD.Core.Coerce
    - SAD.Core.TPTP
    - SAD.Data.Formula
    - SAD.Data.Formula.Base
    - SAD.Data.Formula.Kit
    - SAD.Data.Formula.Show
    - SAD.Data.Terms
    - SAD.Data.VarName
    - SAD.ForTheL.Base
    - SAD.ForTheL.Extension
    - SAD.ForTheL.Instruction
    - SAD.ForTheL.Pattern
    - SAD.ForTheL.Reports
    - SAD.ForTheL.Statement
    - SAD.ForTheL.Structure
    - SAD.Helpers
    - SAD.Parser.Base
    - SAD.Parser.Combinators
    - SAD.Parser.Primitives
    - SAD.Parser.Token

executables:
  Naproche-SAD:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Naproche-SAD
    - Isabelle
    - mtl
    - transformers
    - utf8-string
    - process
    - network
    - uuid
    - threads

tests:
  Naproche-SAD-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Naproche-SAD
    - process
