name:                naproche
version:             0.1.0.0
github:              "naproche/naproche"
license:             GPL-3

extra-source-files:
- README.md

description:         <https://github.com/naproche/naproche>

dependencies:
- base >= 4.13 && < 5
- containers
- unordered-containers
- deepseq
- filepath
- directory
- binary
- ghc-prim
- hashable
- time
- mtl
- bytestring
- text
- split
- aeson
- prettyprinter
- monad-validate

default-extensions:
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - LambdaCase
  - PartialTypeSignatures
  - ScopedTypeVariables
  - DeriveGeneric

ghc-options:
  - -O2
  - -Wall
  - -fno-warn-unused-do-bind
  - -fno-warn-unused-matches
  - -fno-warn-name-shadowing

library:
  source-dirs:
    - src
    - Isabelle/src
  exposed-modules:
    - SAD.Core.AST
    - SAD.Core.Cache
    - SAD.Core.Coerce
    - SAD.Core.Desuger
    - SAD.Core.Errors
    - SAD.Core.Lean
    - SAD.Core.Prove
    - SAD.Core.Provers
    - SAD.Core.Reader
    - SAD.Core.TPTP
    - SAD.Core.Tactic
    - SAD.Core.Task
    - SAD.Core.Transform
    - SAD.Core.Typecheck
    - SAD.Core.Typed
    - SAD.Core.Unique
    - SAD.Data.Identifier
    - SAD.Data.Instr
    - SAD.Data.Message
    - SAD.Data.SourcePos
    - SAD.Data.Text.Block
    - SAD.Main
  other-modules:
    - Isabelle.Markup
    - Isabelle.Value
    - Isabelle.Naproche
    - Isabelle.Library
    - Isabelle.Properties
    - Isabelle.Symbol
    - SAD.Data.Formula
    - SAD.Data.Formula.Base
    - SAD.Data.Formula.Kit
    - SAD.Data.Formula.Show
    - SAD.Data.Terms
    - SAD.Data.VarName
    - SAD.ForTheL.Base
    - SAD.ForTheL.Extension
    - SAD.ForTheL.Instruction
    - SAD.ForTheL.Pattern
    - SAD.ForTheL.Reports
    - SAD.ForTheL.Statement
    - SAD.ForTheL.Structure
    - SAD.Helpers
    - SAD.Parser.Base
    - SAD.Parser.Combinators
    - SAD.Parser.Error
    - SAD.Parser.Primitives
    - SAD.Parser.Token